name: Network Test

on:
  push:
    branches:
      - main

jobs:
  test_network:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: actions/setup-docker@v2

    - name: Build Docker Image
      run: docker build -t network-test .

    - name: Run Network Test
      run: docker run --rm network-test bash -c "ping -c 4 127.0.0.1"
